export const themes = [
  {
    id: "clinica",
    number: "01",
    title: "Na clínica dentária",
    short: "Clínica dentária",
    description: "Profissionais, pessoas e espaços da clínica.",
    color: "#079eb3",
    light: "#dff8fb",
    items: [
      {
        id: "dentista",
        word: "Dentista",
        image: "imagens/01_dentista.png",
        video: "assets/videos/Dentista.mp4",
        youtubeId: "EBtvL2n6vQ0",
        quizPrompt: "Que profissional observa, previne e trata problemas de saúde oral?",
        definition: "O dentista é o profissional de saúde que observa, previne e trata problemas dos dentes, das gengivas e da boca.",
        sentence: "O dentista observa os dentes do paciente.",
      },
      {
        id: "assistente",
        word: "Assistente dentária",
        image: "imagens/02_assistente.png",
        video: "assets/videos/Assistente Dentario.mp4",
        youtubeId: "q3FRB3oDFI0",
        quizPrompt: "Quem prepara os instrumentos e apoia o profissional durante a consulta?",
        definition: "A assistente dentária apoia o dentista durante a consulta, prepara os materiais e ajuda a manter o consultório organizado.",
        sentence: "A assistente dentária prepara os instrumentos para a consulta.",
      },
      {
        id: "paciente",
        word: "Paciente",
        image: "imagens/03_paciente.png",
        video: "assets/videos/Paciente.mp4",
        youtubeId: "yVDPzVkv6TA",
        quizPrompt: "Como se chama a pessoa que recebe cuidados durante uma consulta?",
        definition: "O paciente é a pessoa que vai ao dentista para cuidar da sua saúde oral.",
        sentence: "O paciente está na consulta.",
      },
      {
        id: "consultorio",
        word: "Consultório",
        image: "imagens/04_consultorio.png",
        video: "assets/videos/Consultorio.mp4",
        youtubeId: "2_fmRYFmuGk",
        quizPrompt: "Em que sala da clínica são realizados os exames e os tratamentos?",
        definition: "O consultório é a sala onde o dentista atende o paciente e realiza os tratamentos.",
        sentence: "O dentista trabalha no consultório.",
      },
      {
        id: "sala-espera",
        word: "Sala de espera",
        image: "imagens/05_sala_espera.png",
        video: "assets/videos/Sala De Espera.mp4",
        youtubeId: "0THkOgh5bEY",
        quizPrompt: "Em que espaço da clínica as pessoas aguardam até serem chamadas?",
        definition: "A sala de espera é o espaço onde os pacientes aguardam pela consulta.",
        sentence: "O paciente espera na sala de espera pela sua vez.",
      },
      {
        id: "rececionista",
        word: "Rececionista",
        image: "imagens/06_rececionista.png",
        video: "assets/videos/Rececionista.mp4",
        youtubeId: "6Hn6cyRBFOw",
        quizPrompt: "Quem recebe as pessoas, confirma marcações e fornece informações à entrada da clínica?",
        definition: "A rececionista é a profissional que recebe os pacientes, confirma as marcações e dá informações na receção da clínica.",
        sentence: "O paciente fala com a rececionista quando chega à clínica.",
      },
    ],
  },
  {
    id: "boca",
    number: "02",
    title: "Conhecer a boca",
    short: "Conhecer a boca",
    description: "Partes da boca e estruturas relacionadas.",
    color: "#079eb3",
    light: "#dff8fb",
    items: [
      {
        id: "boca",
        word: "Boca",
        image: "imagens/07_boca.png",
        video: "assets/videos/Boca.mp4",
        youtubeId: "xYKPJSK2EYQ",
        quizPrompt: "Que parte do corpo reúne os dentes, as gengivas e a língua?",
        definition: "A boca é a parte do corpo onde se encontram os dentes, as gengivas e a língua.",
        sentence: "Abrimos a boca para o dentista observar os dentes.",
      },
      {
        id: "dentes",
        word: "Dentes",
        image: "imagens/08_dentes.png",
        video: "assets/videos/Dentes.mp4",
        youtubeId: "NBdQsBb0TDE",
        quizPrompt: "Que estruturas ajudam a cortar e mastigar os alimentos e também participam na fala?",
        definition: "Os dentes ajudam a mastigar os alimentos e também são importantes para falar.",
        sentence: "Devemos cuidar dos dentes todos os dias.",
      },
      {
        id: "gengivas",
        word: "Gengivas",
        image: "imagens/09_gengivas.png",
        video: "assets/videos/Gengivas.mp4",
        youtubeId: "Y4d81_3XiOQ",
        quizPrompt: "Que tecidos rodeiam e ajudam a proteger a base dos dentes?",
        definition: "As gengivas são os tecidos que envolvem e ajudam a proteger os dentes.",
        sentence: "Devemos escovar suavemente junto às gengivas.",
      },
      {
        id: "lingua",
        word: "Língua",
        image: "imagens/10_lingua.png",
        video: "assets/videos/Lingua.mp4",
        youtubeId: "7q9YAMxogBo",
        quizPrompt: "Que órgão muscular permite saborear, engolir e articular a fala?",
        definition: "A língua ajuda a saborear os alimentos, a engolir e a falar.",
        sentence: "A língua também deve ser limpa.",
      },
      {
        id: "labios",
        word: "Lábios",
        image: "imagens/11_labios.png",
        video: "assets/videos/Labios.mp4",
        youtubeId: "iVVbayajF64",
        quizPrompt: "Que estruturas móveis ajudam a fechar a boca, a falar e a expressar emoções?",
        definition: "Os lábios ajudam a fechar a boca, a falar e a expressar emoções.",
        sentence: "O dentista observa os lábios e a boca.",
      },
      {
        id: "maxilares",
        word: "Maxilares",
        image: "imagens/12_maxilares.png",
        video: "assets/videos/Maxilares.mp4",
        youtubeId: "1cm1h5HOQyE",
        quizPrompt: "Que ossos sustentam os dentes e participam nos movimentos da mastigação?",
        definition: "Os maxilares são os ossos que sustentam os dentes e ajudam nos movimentos da boca.",
        sentence: "Os dentes encontram-se nos maxilares.",
      },
    ],
  },
  {
    id: "cuidados",
    number: "03",
    title: "Cuidados de saúde oral",
    short: "Saúde oral",
    description: "Objetos, ações e hábitos para cuidar da boca.",
    color: "#079eb3",
    light: "#dff8fb",
    items: [
      {
        id: "escova",
        word: "Escova de dentes",
        image: "imagens/13_escova_dentes.png",
        video: "assets/videos/Escova De Dentes.mp4",
        youtubeId: "bSx66fRsqVg",
        quizPrompt: "Que objeto com cabo e cerdas é usado na limpeza diária da boca?",
        definition: "A escova de dentes é utilizada para remover restos de alimentos e placa bacteriana dos dentes.",
        sentence: "Colocamos pasta dentífrica na escova de dentes.",
      },
      {
        id: "pasta",
        word: "Pasta dentífrica",
        image: "imagens/14_pasta_dentifrica.png",
        video: "assets/videos/Pasta Dentifrica.mp4",
        youtubeId: "pn1KuRXsILI",
        quizPrompt: "Que produto é colocado nas cerdas para ajudar a limpar e proteger a superfície dentária?",
        definition: "A pasta dentífrica é um produto usado com a escova para ajudar a limpar e proteger os dentes.",
        sentence: "Usamos uma pequena quantidade de pasta dentífrica.",
      },
      {
        id: "fio",
        word: "Fio dentário",
        image: "imagens/15_fio_dentario.png",
        video: "assets/videos/Fio Dentario.mp4",
        youtubeId: "PK8JIpzGigo",
        quizPrompt: "Que recurso fino limpa os espaços onde as cerdas não chegam facilmente?",
        definition: "O fio dentário ajuda a limpar os espaços entre os dentes, onde a escova não chega facilmente.",
        sentence: "O fio dentário passa suavemente entre os dentes.",
      },
      {
        id: "colutorio",
        word: "Colutório",
        image: "imagens/16_colutorio.png",
        video: "assets/videos/Colutorio.mp4",
        youtubeId: "oANMlZKHPSM",
        quizPrompt: "Que líquido pode ser usado para bochechar quando recomendado por um profissional?",
        definition: "O colutório é um líquido utilizado para bochechar, quando recomendado por um profissional de saúde oral.",
        sentence: "O colutório não deve ser engolido.",
      },
      {
        id: "escovar",
        word: "Escovar os dentes",
        image: "imagens/17_escovar_dentes.png",
        video: "assets/videos/Escovar Dentes.mp4",
        youtubeId: "mtQhDy-ncVw",
        quizPrompt: "Que ação diária remove a placa bacteriana das superfícies dentárias?",
        definition: "Escovar os dentes ajuda a remover a placa bacteriana e a prevenir problemas de saúde oral.",
        sentence: "Devemos escovar todas as superfícies dos dentes.",
      },
      {
        id: "consulta-rotina",
        word: "Consulta de rotina",
        image: "imagens/18_consulta_rotina.png",
        video: "assets/videos/Consulta De Rotina.mp4",
        youtubeId: "ODOWZxOyK9s",
        quizPrompt: "Que tipo de visita permite verificar a boca e identificar precocemente possíveis problemas?",
        definition: "A consulta de rotina permite ao dentista observar a boca, verificar os dentes e identificar possíveis problemas.",
        sentence: "O paciente vai ao dentista para uma consulta de rotina.",
      },
    ],
  },
];

export const trueFalseStatements = {
  clinica: [
    {
      id: "clinica-1",
      statement: "O dentista observa e trata problemas dos dentes.",
      answer: true,
      explanation: "O dentista observa, previne e trata problemas dos dentes, das gengivas e da boca.",
    },
    {
      id: "clinica-2",
      statement: "A assistente dentária espera pela consulta como paciente.",
      answer: false,
      explanation: "A assistente dentária apoia o dentista, prepara os materiais e ajuda a organizar o consultório.",
    },
    {
      id: "clinica-3",
      statement: "O paciente vai à clínica para cuidar da sua saúde oral.",
      answer: true,
      explanation: "O paciente é a pessoa que vai ao dentista para cuidar da sua saúde oral.",
    },
    {
      id: "clinica-4",
      statement: "O consultório é a sala onde os pacientes esperam pela sua vez.",
      answer: false,
      explanation: "O consultório é a sala onde o dentista atende o paciente. Os pacientes aguardam na sala de espera.",
    },
    {
      id: "clinica-5",
      statement: "A sala de espera é o local onde os pacientes aguardam.",
      answer: true,
      explanation: "A sala de espera é o espaço onde os pacientes aguardam pela consulta.",
    },
    {
      id: "clinica-6",
      statement: "A rececionista confirma marcações e dá informações.",
      answer: true,
      explanation: "A rececionista recebe os pacientes, confirma as marcações e dá informações.",
    },
  ],
  boca: [
    {
      id: "boca-1",
      statement: "A boca contém os dentes, as gengivas e a língua.",
      answer: true,
      explanation: "A boca é a parte do corpo onde se encontram os dentes, as gengivas e a língua.",
    },
    {
      id: "boca-2",
      statement: "Os dentes servem apenas para sorrir.",
      answer: false,
      explanation: "Os dentes ajudam a mastigar os alimentos e também são muito importantes para falar.",
    },
    {
      id: "boca-3",
      statement: "As gengivas envolvem e protegem os dentes.",
      answer: true,
      explanation: "As gengivas envolvem e ajudam a proteger os dentes.",
    },
    {
      id: "boca-4",
      statement: "A língua ajuda a engolir e a falar.",
      answer: true,
      explanation: "A língua ajuda a saborear os alimentos, a engolir e a falar.",
    },
    {
      id: "boca-5",
      statement: "Os lábios ajudam a fechar a boca.",
      answer: true,
      explanation: "Os lábios ajudam a fechar a boca, a falar e a expressar emoções.",
    },
    {
      id: "boca-6",
      statement: "Os maxilares são músculos da língua.",
      answer: false,
      explanation: "Os maxilares são os ossos que sustentam os dentes.",
    },
  ],
  cuidados: [
    {
      id: "cuidados-1",
      statement: "A escova de dentes ajuda a remover placa bacteriana.",
      answer: true,
      explanation: "A escova de dentes remove restos de alimentos e placa bacteriana dos dentes.",
    },
    {
      id: "cuidados-2",
      statement: "A pasta dentífrica é utilizada sem a escova de dentes.",
      answer: false,
      explanation: "A pasta dentífrica é utilizada com a escova para ajudar a limpar e proteger os dentes.",
    },
    {
      id: "cuidados-3",
      statement: "O fio dentário limpa os espaços entre os dentes.",
      answer: true,
      explanation: "O fio dentário ajuda a limpar os espaços entre os dentes, onde a escova não chega facilmente.",
    },
    {
      id: "cuidados-4",
      statement: "O colutório deve ser engolido depois de bochechar.",
      answer: false,
      explanation: "O colutório é utilizado para bochechar e não deve ser engolido.",
    },
    {
      id: "cuidados-5",
      statement: "Escovar os dentes ajuda a prevenir problemas de saúde oral.",
      answer: true,
      explanation: "Escovar os dentes remove a placa bacteriana e ajuda a prevenir problemas de saúde oral.",
    },
    {
      id: "cuidados-6",
      statement: "A consulta de rotina só é necessária quando existe dor.",
      answer: false,
      explanation: "A consulta de rotina permite verificar os dentes e identificar possíveis problemas, mesmo quando não existe dor.",
    },
  ],
};
